# --- Qatten ---

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
runner: "episode"
buffer_size: 5000
target_update_interval: 200
agent_output_type: "q"
learner: "dmaq_qatten_rnd_learner"
double_q: True
mixer: "dmaq_qatten"
mixing_embed_dim: 32
hypernet_embed: 64
adv_hypernet_layers: 1
adv_hypernet_embed: 64
num_kernel: 4
is_minus_one: True
is_adv_attention: True
is_stop_gradient: True
n_head: 4  
attend_reg_coef: 0.01 
state_bias: True
mask_dead: False
weighted_head: False
nonlinear: False  
burn_in_period: 100
name: "qplex_rnd"
RND_hidden_dim: 64
model_type: 1
kl_lambda: 0 
seed: 30
atc_pretrain: 1500000
atc_decay: 1200000
decay_coefficient: 0.0 
rnd_start_train: 500000
tau: 0.000 
tau_pred: 0.0 
tau_tgt: 0.0 
intrinsic_scale: 0.5 

